const C = {
  /** User actions **/
  STORE_SAVING_REQUEST: 'STORE_SAVING_REQUEST',

  LOAD_MANIFEST: 'LOAD_MANIFEST',
  MATCH_SELECTION: 'MATCH_SELECTION',
  UNMATCH: 'UNMATCH',
  SELECT_EXPECTED_OPTION: 'SELECT_EXPECTED_OPTION',
  SELECT_OBSERVED_OPTION: 'SELECT_OBSERVED_OPTION',

  SET_MANIFEST_VALUE: 'SET_MANIFEST_VALUE',
  CHANGE_TAB: 'CHANGE_TAB',
  DISPLAY_MESSAGE: 'DISPLAY_MESSAGE',
  SAVE_TAB: 'SAVE_TAB',
  TOGGLE_MAPPING: 'TOGGLE_MAPPING',

  CACHE_TAXONOMY: 'CACHE_TAXONOMY',
  SET_TAXONOMY_NUM_CALLS: 'SET_TAXONOMY_NUM_CALLS',

  SAVE_AND_LEAVE: 'SAVE_AND_LEAVE'
}

export default C
