const constants = {
  /** User actions **/
  MATCH_FIELDS: 'MATCH_FIELDS',
  UMMATCH_FIELDS: 'UNMATCH_FIELDS',

  CHANGE_TAB: 'CHANGE_TAB',
  SET_VALUE_TO_FIELD: 'SET_VALUE_TO_FIELD',
  REMOVE_MESSAGE: 'REMOVE_MESSAGE',

  /** **/
  SAVE_TAB: 'SAVE_TAB',
  RESTORE_TAB: 'RESTORE_TAB',
  VALIDATE_FIELD: 'VALIDATE_FIELD',
  VALIDATE_MATERIAL: 'VALIDATE_MATERIAL',
  VALIDATE_TAB: 'VALIDATE_TAB',
  VALIDATE_MANIFEST: 'VALIDATE_MANIFEST'
}
